-- ============================================================================
-- DEPRECATED — DO NOT EDIT THIS FILE
-- ============================================================================
-- The single canonical database schema lives at:
--
--   /supabase_schema.sql
--
-- This nested copy was retained only as a redirect notice so older docs/scripts
-- that pointed at supabase/schema.sql fail loudly instead of applying a stale
-- subset of tables (missing language_configs, zodiac_configs, interest_configs,
-- creator target columns, burn_call_coins_atomic, etc.).
--
-- Action required:
--   1. Open /supabase_schema.sql
--   2. Paste it into the Supabase SQL Editor and run it
--   3. Or fetch it via GET /api/admin/schema
--
-- ============================================================================

DO $$
BEGIN
  RAISE EXCEPTION
    'DEPRECATED: Use /supabase_schema.sql (project root) as the single canonical schema. supabase/schema.sql is no longer maintained.';
END $$;
